version: "3"
services:
  ems-docker:
    build:
      context: .
      dockerfile: ./DockerFile
    image: ems-docker-app:latest
    container_name: ems-docker
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: ems-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: ems-mongo-express
    restart: always
    ports:
        - "8081:8081"
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
        ME_CONFIG_MONGODB_SERVER: ems-mongo
    depends_on:
      - mongo

volumes:
    data: {}

networks:
   default:
      name: mongodb_network